---
title: "CITS5507 Project 1: Parallel implementation of search based on Fish School Behaviour"

graphics: yes
author: Kaiqi Liang (23344153), Briana Davies-Morrell (22734723)
date: "Semester 2, 2023"

output:
  html_document:
    number_sections: true
---

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(ggplot2)
```

# Experimenting with Number of Threads 
Fix everything but number of threads

```{r, message=FALSE, warning=FALSE, echo=FALSE}
ggplot(
    data.frame(
      num_threads = seq(7),
      time = c(
        2780.588561,
        3220.587380,
        3471.353496,
        2925.219894,
        2944.861335,
        2929.350958,
        3000.694720)),
    aes(x = num_threads, y = time)) +
    labs(x = "Number of Threads", y = "Time (s)") +
    scale_x_continuous(
      breaks = seq(7),
      labels = c("Sequential", 1, 2, 4, 6, 8, 16)) +
    geom_point() +
    geom_smooth()
```


# Experimenting with Number of Fish & Iterations 

default, no scheduling 
set at 4 threads 
change iterations AND fish 

```{r, message=FALSE, warning=FALSE, echo=FALSE}

ggplot(
  data = data.frame(
    num_fish =  c(200000, 400000, 600000, 800000, 1000000),
    iter_20000 = c(117.350819,237.082449,397.935612,482.203047, 653.402037),
    iter_40000 = c(234.463991,466.925614,700.021926,936.720754,1177.662832),
    iter_60000 = c(353.012268,701.901361,1050.975947,1418.876797,1777.164701),
    iter_80000 = c(471.402103,944.524666,1397.776130,1863.592248,2350.380621),
    iter_100000 = c(586.554482, 1167.285182, 1697.776130,2363.592248, 2925.219894)),
  aes(x = num_fish)) +
  geom_smooth(aes(y = iter_20000, color = "20000")) +
  geom_smooth(aes(y = iter_40000, color = "40000")) +
  geom_smooth(aes(y = iter_60000, color = "60000")) +
  geom_smooth(aes(y = iter_80000, color = "80000")) +
  geom_smooth(aes(y = iter_100000, color = "100000")) +
  geom_point(aes(y = iter_20000)) +
  geom_point(aes(y = iter_40000)) +
  geom_point(aes(y = iter_60000)) +
  geom_point(aes(y = iter_80000)) +
  geom_point(aes(y = iter_100000)) +
  labs(x = "Number of Fish",
    y = "Time (s)",
    color = "Number of Iterations") +
  scale_color_manual(values = c(
    "20000" = "darkred",
    "40000" = "steelblue",
    "60000" = "magenta",
    "80000" = "darkgreen",
    "100000" = "pink4"))
```

# Kaiqi 
Fix number of threads to be 4, change chunk size and scheduling types

```{r, message=FALSE, warning=FALSE, echo=FALSE}
ggplot(
  data = data.frame(
    chunk_size = c(1, 2, 3, 4),
    static = c(3000, 2784.864581, 3000, 2918.142244),
    dynamic = c(3000, 3073.691588, 3000, 2982.671884),
    guided = c(3000, 3000, 3000, 2946.995764),
    runtime = 3000),
  aes(x = chunk_size)) +
  geom_smooth(aes(y = static, color = "static")) +
  geom_smooth(aes(y = dynamic, color = "dynamic")) +
  geom_smooth(aes(y = guided, color = "guided")) +
  geom_smooth(aes(y = runtime, color = "runtime")) +
  geom_point(aes(y = static)) +
  geom_point(aes(y = dynamic)) +
  geom_point(aes(y = guided)) +
  geom_point(aes(y = runtime)) +
  labs(x = "Chunk Size",
    y = "Time (s)",
    color = "Scheduling Type") +
  scale_x_continuous(labels = c(1, 10, 100, 10000)) +
  scale_color_manual(values = c(
    "static" = "darkred",
    "dynamic" = "steelblue",
    "guided" = "magenta",
    "runtime" = "darkgreen"))
```

Fix everything but different implementation of tasks vs partition and simple parallel for
